name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        php_version: 7.4
        configuration: phpunit.xml
        memory_limit: 256M
        bootstrap: bootstrap.php

    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ddfc64b8aa29f4d841ab52f394e43482
        filename: test.json
        label: build
        message: passing
        color: green

    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 3b3f9a428e84a26e8cdf64bd5b83e5d9
        filename: test.json
        label: coverage
        message: 100%
        color: green
